### ISSUE TITLE
Telegram Instant View Support

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#1]
Instant View allows Telegram users to view articles from around the Web in a consistent way, with zero loading time. When you get a link to an article via Telegram, simply tap the Instant View button, and the page will open instantly.

https://instantview.telegram.org/

`<meta name="telegram:channel" content=“@flyvemdm”>`

**Comment by Gianfranco97** [comment]
## Working on Telegram Instant Views. At the moment I can not get them to work outside of the template editor.
![captura de pantalla 2017-08-11 a la s 10 21 48 a m](https://user-images.githubusercontent.com/19965590/29217255-2bce399a-7e7f-11e7-9711-9772adc4e0dc.png)
![captura de pantalla 2017-08-11 a la s 10 22 24 a m](https://user-images.githubusercontent.com/19965590/29217262-31d3c44a-7e7f-11e7-8b81-8e9eeee6ac9e.png)

**Comment by ajsb85** [comment]
@Gianfranco97 You can get support here: https://t.me/IVpublic

**Comment by ajsb85** [comment]
This is my IV for https://flyve-mdm.github.io/flyve-mdm-android-inventory/

![imagen](https://user-images.githubusercontent.com/663460/29313428-3c9b0058-81ba-11e7-8ee6-aae2841b7cb3.png)

**Comment by Gianfranco97** [comment]
1.  Instant Views is only working for our articles of news
2. Instaview links need to have a special structure to work https://instantview.telegram.org/#publishing-templates

**Comment by Gianfranco97** [comment]
## Tables not supported 
![captura de pantalla 2017-08-15 a la s 12 11 28 p m](https://user-images.githubusercontent.com/19965590/29324709-115fefae-81b3-11e7-8d21-1f8ad75200e2.png)

**Comment by Monsenjore** [comment]
Good day. Did you solve the problem with table? They are still not supported bur maybe there is some way to replace it for example for list?

**Comment by Gianfranco97** [comment]
the problem was solved in part, what it was done was to include a condition in the template that removes the tables and the "<hr />" tags that are immediately before

**Comment by Monsenjore** [comment]
So to solve the problem I should just remove all tables?
