### ISSUE TITLE
prose.io badly configured 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#15]
Hi, @Gianfranco97 

Could you check the YAML config for Prose?

I can not see the `_post` folder that you mention in your issue https://github.com/flyve-mdm/flyve-mdm-ios-inventory/issues/57

![imagen](https://user-images.githubusercontent.com/663460/29708795-5074b6dc-898a-11e7-91d3-6b0800bebd4f.png)

Example of how looks a good configuration:

![imagen](https://user-images.githubusercontent.com/663460/29708824-6b9a3d74-898a-11e7-8664-cf7210bef078.png)

**Comment by Gianfranco97** [comment]
What happens is that git does not take into account empty folders. Here is the explanation and solution: https://www.git-tower.com/learn/git/faq/add-empty-folder-to-version-control

**Comment by Gianfranco97** [comment]
### Problem resulted
