### ISSUE TITLE
Multiple changes request for the configurations of the project sites

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#16]
Hi, @Gianfranco97 

Please, review these changes for `.gitignore` and the `_config.yml` files.

## Files to `.gitignore`

This is a cache folder generate by Jekyll (on GitHub) in the render process
`.sass-cache`

This is a static folder generate by Jekyll (on GitHub) in the render process
`_site`

File that stores custom attributes of its containing folder in Mac OS
`.DS_Store`

## Changes for the YAML config of Jekyll

`email: ml-flyvemdm@teclib.com`

I think these fields are useless:
`url, baseurl, repository`

It's in the metadata from GitHub.

**Comment by Gianfranco97** [comment]
Hi @ajsb85 

The fields ```url, baseurl and repository``` if they are necessary for the operation of the site. In fact without its existence nothing would work.

**Comment by ajsb85** [comment]
@Gianfranco97 Here is an example of the blog without these configurations:

https://github.com/rsms/rsms.github.com/blob/master/_config.yml

The idea is to create a template more easy to maintenance.

**Comment by Gianfranco97** [comment]
The filter ```"| relative url"``` uses the attribute ```baseurl``` for its operation, the elimination of this attribute would create conflicts between the distinton gh-pages because they use the same url

**Comment by Gianfranco97** [comment]
Email and .gitignore updated 

![captura de pantalla 2017-08-25 a la s 11 23 13 a m](https://user-images.githubusercontent.com/19965590/29720470-0644c324-8988-11e7-8784-a648a8059229.png)


![captura de pantalla 2017-08-25 a la s 11 25 12 a m](https://user-images.githubusercontent.com/19965590/29720693-bf4868b2-8988-11e7-99b9-ddacfecb9841.png)
