### ISSUE TITLE
How to handle issues

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#19]
Hi, @ajsb85 

I have a question, how should I handle the project ready tasks? ...
The "merge in develop" and "merge in master" categories lose their meaning in gh-pages.

Thanks in advance.

**Comment by ajsb85** [comment]
@Gianfranco97 Every repository have a project called Website with 3 columns: Backlog, Tasks in Progress and Done.

**Comment by Gianfranco97** [comment]
![captura de pantalla 2017-08-25 a la s 4 13 45 p m](https://user-images.githubusercontent.com/19965590/29730948-787c9048-89b0-11e7-9b4a-2def3912a130.png)

**Comment by ajsb85** [comment]
![capture _2017-08-25-22-21-48](https://user-images.githubusercontent.com/663460/29731202-db67ac32-89e3-11e7-94c6-996e3ac4ee4a.png)

**Comment by Gianfranco97** [comment]
## Yes, I'm already using this project
![captura de pantalla 2017-08-25 a la s 5 53 22 p m](https://user-images.githubusercontent.com/19965590/29734159-aceb4fc8-89be-11e7-80e7-61ee5fea4468.png)

**Comment by ajsb85** [comment]
@Gianfranco97 Already edited the columns. 👍🏻

**Comment by Gianfranco97** [comment]
Thank you 👍
