### ISSUE TITLE
Code documentation theme for iOS projects

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#22]
Hi, @Gianfranco97 

Could you add a new item in the menu for the code documentation?
And add a folder (like _docs) with the sources of the documentation generate with a custom theme with our guidelines.
https://github.com/realm/jazzy#themes

Thanks.

**Comment by Gianfranco97** [comment]
Done 
![localhost-4000-flyve-mdm-ios-agent-docs-classes-formrow-dateconfiguration html 1](https://user-images.githubusercontent.com/19965590/29947096-f0e47478-8e75-11e7-887f-af8426853078.png)

**Comment by ajsb85** [comment]
Wow. 

I want to see how looks like.

**Comment by Gianfranco97** [comment]
it's necessary to change the configuration of the repository, the branch gh-pages is not dissociated as the website

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Already changed the folder and the branch for the project site of the MDM Agent for iOS

 https://flyve-mdm.github.io/flyve-mdm-ios-agent/.
