### ISSUE TITLE
Code documentation for Java projects

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#23]
Hi, @Gianfranco97 

Could you add a new item in the menu for the code documentation?
And add a folder (like _docs) with the sources of the documentation generate with a custom theme with our guidelines.

Javadoc for code documentation from the fork of @rafaelje 
https://rafaelje.github.io/flyve-mdm-android-agent/javadoc/

Thanks.

**Comment by Gianfranco97** [comment]
This is already done. 

For more information:
https://github.com/flyve-mdm/flyve-mdm-android-admin-dashboard/issues/19
https://github.com/flyve-mdm/flyve-mdm-android-inventory/issues/25
https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/28
https://github.com/flyve-mdm/flyve-mdm-android-agent/issues/153
