### ISSUE TITLE
Quality reports for project sites

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#24]
Hi, @Gianfranco97 

Please add a new item in the menu (Development) for the Java projects, and sub items for Code Documemtation, Code Coverage, and Test Reports.

More information about the code documentation:
https://github.com/flyve-mdm/flyve-mdm-press-kit/issues/23

Code Coverage Using JaCoCo <https://github.com/jacoco/jacoco>
https://rafaelje.github.io/flyve-mdm-android-agent/app/build/reports/coverage/debug/

Test Report
https://rafaelje.github.io/flyve-mdm-android-agent/app/build/reports/androidTests/connected/

**Comment by Gianfranco97** [comment]
This is already done. 

For more information:
https://github.com/flyve-mdm/flyve-mdm-android-admin-dashboard/issues/19
https://github.com/flyve-mdm/flyve-mdm-android-inventory/issues/25
https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/28
https://github.com/flyve-mdm/flyve-mdm-android-agent/issues/153
