### ISSUE TITLE
Fix URL for Test Report Android

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-press-kit#32]
Hi, @Gianfranco97 

Please change the link to the "Test Report" on Documentation 

This is the actual link http://flyve.org/flyve-mdm-android-inventory/reports/androidTests/
and this would be http://flyve.org/flyve-mdm-android-inventory/reports/androidTests/connected

Thanks.

**Comment by Gianfranco97** [comment]
done
