### ISSUE TITLE
Different CSS on Documentation Android

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/flyve-mdm-press-kit#35]
Hi, @Gianfranco97 

Please check the css of this files has three different fonts on menu bar and footer:

- http://flyve.org/flyve-mdm-android-inventory/reports/javadoc/
- http://flyve.org/flyve-mdm-android-inventory/reports/debug/
- http://flyve.org/flyve-mdm-android-inventory/reports/androidTests/connected/

Thanks.

**Comment by Gianfranco97** [comment]
I've updated the style sheet for javadoc and created a modified version of the styles of coverage.

- https://gist.github.com/Gianfranco97/1c851a3c008bc1abc9d7560a8787a949

- https://gist.github.com/Gianfranco97/0bb8441af4b39059f0e03c3c55408b18

it will be necessary to replace the file of the style sheet of coverage in ours, the route is the following one:
reports / debug / resources / report.css

**Comment by ajsb85** [comment]
@Gianfranco97 I will fork in the bot of Flyve MDM on GitHub

**Comment by ajsb85** [comment]
@Gianfranco97 Already added and updated

https://gist.github.com/flyve-mdm-bot
