### ISSUE TITLE
Fix Javadoc styles 

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#38]
I'm going to fix some buttons from the Javadoc documentation that are out of position.

![captura de pantalla 2017-09-28 a la s 9 44 20 a m](https://user-images.githubusercontent.com/19965590/30970326-e3978954-a432-11e7-9cdd-be765c68ffe0.png)

**Comment by Gianfranco97** [comment]
**ready**, here is the updated code: 
- https://gist.github.com/Gianfranco97/1c851a3c008bc1abc9d7560a8787a949
![captura de pantalla 2017-09-28 a la s 10 32 22 a m](https://user-images.githubusercontent.com/19965590/30972375-60f1638e-a438-11e7-92aa-d03aaf9f7970.png)

**Comment by ajsb85** [comment]
@Gianfranco97 @Rafaelje Hi,
Please push the file in the gh-pages and only change the link in the header of the layout. To avoid the usage of gist.
