### ISSUE TITLE
Images for Reddit

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#40]
Hi, @mmillevoye 

It is necessary to create the images of Flyve MDM for mobile Reddit, they must be two, one as an icon, which should be 256x256 pixels and another that will do the header function, this has to have a 10: 3. Both pictures should be in PNG format, although it would also be useful to have the editable ones.

- image of the qualifier where these images are required:
![captura de pantalla 2017-10-04 a la s 2 59 22 p m](https://user-images.githubusercontent.com/19965590/31194838-57297f3e-a916-11e7-906f-27934e831e8f.png)

- image of the context where they will be displayed:
![photo5093739142298314670](https://user-images.githubusercontent.com/19965590/31194918-9413e966-a916-11e7-922e-f2207a37ffe4.jpg)

These are to be delivered as soon as possible.

Thank you.

**Comment by mmillevoye** [comment]
![flyve-banner](https://user-images.githubusercontent.com/29282308/31217022-e44b2c60-a9b5-11e7-8834-eca1ef0a3891.png)
![flyve-icon](https://user-images.githubusercontent.com/29282308/31217021-e44969e8-a9b5-11e7-9a03-f74463d16496.png)
 Hi ! What text do you need on the banner ?

**Comment by Gianfranco97** [comment]
@mmillevoye  not at the moment, first we need to see as it remains to know if it is necessary to change something. But we have a problem with the resolutions of the banner image.

![captura de pantalla 2017-10-05 a la s 3 19 29 p m](https://user-images.githubusercontent.com/19965590/31248522-07e4991e-a9e2-11e7-85fe-dd7fdd3a419f.png)

**Comment by Gianfranco97** [comment]
I forced the resolution of the image to be able to do tests, that's how it looks: 
![www reddit com-r-flyvemdm-](https://user-images.githubusercontent.com/19965590/31251667-c23248fc-a9ec-11e7-8ec8-4840536c7e66.png)

**Comment by mmillevoye** [comment]
![flyve-banner](https://user-images.githubusercontent.com/29282308/31268116-290aec3a-aa7b-11e7-9927-8a4f00e134dd.png)
Here is the header banner in 1280x384 resolution.

**Comment by ajsb85** [comment]
Merci

![capture _2017-10-06-03-48-46](https://user-images.githubusercontent.com/663460/31274852-13ff3cfa-aa95-11e7-9a24-80e362a0b712.png)

**Comment by Gianfranco97** [comment]
Thanks for your help @mmillevoye 👍
