### ISSUE TITLE
Winstrap theme for GLPI Network

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#45]
Hi, @Gianfranco97 

Could you create the Winstrap theme for GLPI Network?
I will send you by email the source files of the logotype.
The idea is to create a project site for the projects relates ti GLPI (clients, libraries, etc) as proposal.

Thanks.

**Comment by Gianfranco97** [comment]
![screenshot-2017-10-9 teclib flyve-mdm-bootstrap 1](https://user-images.githubusercontent.com/19965590/31358944-b3ab6828-ad15-11e7-839a-2f04d508ee55.png)
