### ISSUE TITLE
Winstrapp theme for Teclib Edition

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#46]
Hi, @Gianfranco97 

Could you create the Winstrap theme for Teclib Edition?
I will send you by email the vector files of the logotype
The idea is to create a project site for the repositories not related to any registered brand of Teclib.

Thanks.

**Comment by Gianfranco97** [comment]
![screenshot-2017-10-9 teclib flyve-mdm-bootstrap 2](https://user-images.githubusercontent.com/19965590/31359196-f62d076e-ad16-11e7-88f2-0844023648ce.png)
