### ISSUE TITLE
Images for manifest

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#48]
Hi, @mmillevoye 

I need the following images in 512 x 512 px:
 ![ga09nfjh_400x400](https://user-images.githubusercontent.com/19965590/31471712-36ecc792-aeb8-11e7-8e51-fd42026d8e9a.jpg)

 ![19646101](https://user-images.githubusercontent.com/19965590/31471690-0d1218dc-aeb8-11e7-845f-c9fd798a9bf6.png)

these must be flatly flat, this is an example of how they should be:
 
 ![apple-touch-icon](https://user-images.githubusercontent.com/19965590/31471736-580a67b8-aeb8-11e7-90c2-fe4da54960e7.png)

Thanks.

**Comment by mmillevoye** [comment]
Hi @Gianfranco97 
![icon-edition-armadito](https://user-images.githubusercontent.com/29282308/31487751-d2ebc048-af3b-11e7-9a39-94750e26a952.png)
![icon-edition-glpi](https://user-images.githubusercontent.com/29282308/31487752-d304ac02-af3b-11e7-8d44-69731623fea0.png)
All good ?

**Comment by Gianfranco97** [comment]
Yes, thank you very much
