### ISSUE TITLE
Banner for GLPI and Armadito

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#51]
Hi, @mmillevoye 

We need a new banner for GLPI and Armadito with the same specs of the Flyve MDM

![banner](https://user-images.githubusercontent.com/663460/26935464-54267e9c-4c6c-11e7-86df-8cfa6658133e.png)

**Comment by mmillevoye** [comment]
![26935464-54267e9c-4c6c-11e7-86df-8cfa6658133e](https://user-images.githubusercontent.com/29282308/31666124-705391c2-b34b-11e7-84b8-8260856f692e.png)
![armadito-banner](https://user-images.githubusercontent.com/29282308/31666125-70701ba8-b34b-11e7-9d04-f5efb042d58c.png)
Here they are. Is it the right size ?

**Comment by mmillevoye** [comment]
![glpi-banner](https://user-images.githubusercontent.com/29282308/31666160-8ad74b1a-b34b-11e7-839b-043255af4f58.png)

**Comment by ajsb85** [comment]
@mmillevoye Thank you.
It's perfect.
@Naylin15 could you replace the banner in the glpi libraries

**Comment by Naylin15** [comment]
Sure, right away

**Comment by ajsb85** [comment]
@mmillevoye We need also a banner for Teclib Edition (when the project is not associated to any product)

Merci

**Comment by mmillevoye** [comment]
![edition-banner](https://user-images.githubusercontent.com/29282308/31668376-57a730c8-b352-11e7-94fd-6d817de514d4.png)
Like that ?

**Comment by ajsb85** [comment]
Hi, @mmillevoye 

@pascal-teclib said: always the background of the Teclib Edition logo is white.
http://teclib-edition.com/

This image is from the Teclib Edition site:

http://www.teclib-edition.com/wp-content/uploads/bfi_thumb/Home-imageBoost-mv5s45u3gznep056zq0plb72azzh5mlc5r6c13ycu4.jpg

Thank you.

**Comment by mmillevoye** [comment]
![edition-banner](https://user-images.githubusercontent.com/29282308/31669077-552a1a98-b354-11e7-9e62-4677ab8fb1ea.png)
Alright !

**Comment by ajsb85** [comment]
@mmillevoye The background is perfect, but if you can reduce the zoom of the image, will be better.

**Comment by mmillevoye** [comment]
![edition-banner](https://user-images.githubusercontent.com/29282308/31669540-abed67a8-b355-11e7-98e2-0ad190f37088.png)
Here ?

**Comment by ajsb85** [comment]
@mmillevoye Perfect, thank you

**Comment by ajsb85** [comment]
@Naylin15 This Teclib banner is for the `fastlane plugin`, and use the GLPI Network banner for the `orion-glpi-plugin`

**Comment by Naylin15** [comment]
D'accord
