### ISSUE TITLE
Changelog parse in sub pages

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#54]
Hi, @Gianfranco97 

Wrong parser of the changelog in markdown format in this link:

http://flyve.org/flyve-mdm-ios-inventory-agent/docs/Classes/AboutController.html#/s:22FlyveMDMInventoryAgent15AboutControllerC12infoTextViewSo06UITextH0Cv

![image](https://user-images.githubusercontent.com/663460/31780852-35c062a8-b4f7-11e7-95e6-2b60ca9dd04e.png)

**Comment by Gianfranco97** [comment]
Done, problem solved. But it is necessary to make some changes at the moment of generating the changelog, in a moment I create an issue with the new requirements.


![captura de pantalla 2017-10-19 a la s 3 03 10 p m](https://user-images.githubusercontent.com/19965590/31789019-ad4bee1e-b4de-11e7-9417-2092bc99592c.png)
