### ISSUE TITLE
Home Layout - GLPI API Client - Project Sites

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-press-kit#61]
Hi, @Gianfranco97 

After the contributions of @Naylin15 
I can see this issue in the home layout of the project sites for the GLPI API Clients:

![image](https://user-images.githubusercontent.com/663460/32234137-5429c6da-be5c-11e7-885e-529b7d30d8d5.png)

Could you fix it?
Thanks.

**Comment by Gianfranco97** [comment]
Sure @ajsb85, I think I know what the problem is 👍

**Comment by Gianfranco97** [comment]
Done, I talked to @Naylin15 about this. The problem should be solved shortly, this happens simply because the content was not within the class that is responsible for centering it.

**Comment by ajsb85** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/663460/32282066-de780d46-bf20-11e7-8afa-dcf6d2b356b4.png)
